name: 🤔 Question?
description: You have something specific to achieve and the existing documentation hasn't covered how.
title: '[Question]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Please check for an existing issue and our documentation at [README file](https://github.com/skarllot/EnumUtilities#guide) before asking a question.
        Also consider asking your question on [Github Discussions](https://github.com/skarllot/EnumUtilities/discussions) instead.
  - type: textarea
    attributes:
      label: What are you wanting to achieve?
      description: A clear and concise description of what you're trying to do.
      placeholder: I am trying to do [...] but [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: What code or approach do you have so far?
      description: |
        We ❤ code! Point us to a [minimalistic project which shows what you have so far](https://stackoverflow.com/help/mcve) hosted in a public GitHub repository.
        Code snippets wrapped in a codefence are also acceptable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots related to your question here.
    validations:
      required: false
