//HintName: HumanStatesValidation.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

#pragma warning disable CS1591 // publicly visible type or member must be documented

namespace TestNamespace
{
    public static partial class HumanStatesValidation
    {
        public static bool IsDefined(HumanStates value)
        {
            return value switch
            {
                HumanStates.Idle => true,
                HumanStates.Working => true,
                HumanStates.Sleeping => true,
                HumanStates.Eating => true,
                HumanStates.Dead => true,
                _ => false
            };
        }

        public static bool IsDefined(
            [NotNullWhen(true)] string? name,
            StringComparison comparisonType)
        {
            return name switch
            {
                { } s when s.Equals(nameof(HumanStates.Idle), comparisonType) => true,
                { } s when s.Equals(nameof(HumanStates.Working), comparisonType) => true,
                { } s when s.Equals(nameof(HumanStates.Sleeping), comparisonType) => true,
                { } s when s.Equals(nameof(HumanStates.Eating), comparisonType) => true,
                { } s when s.Equals(nameof(HumanStates.Dead), comparisonType) => true,
                { } s when s.Equals(nameof(HumanStates.Relaxing), comparisonType) => true,
                _ => false
            };
        }

        public static bool IsDefinedIgnoreCase([NotNullWhen(true)] string? name)
        {
            return IsDefined(name, StringComparison.OrdinalIgnoreCase);
        }

        public static bool IsDefined([NotNullWhen(true)] string? name)
        {
            return name switch
            {
                nameof(HumanStates.Idle) => true,
                nameof(HumanStates.Working) => true,
                nameof(HumanStates.Sleeping) => true,
                nameof(HumanStates.Eating) => true,
                nameof(HumanStates.Dead) => true,
                nameof(HumanStates.Relaxing) => true,
                _ => false
            };
        }
    }
}
