//HintName: HumanStatesFactory.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

#pragma warning disable CS1591 // publicly visible type or member must be documented

namespace TestNamespace
{
    public static partial class HumanStatesFactory
    {
        public static bool TryParse(
            [NotNullWhen(true)] string? name,
            StringComparison comparisonType,
            out HumanStates result)
        {
            switch (name)
            {
                case { } s when s.Equals(nameof(HumanStates.Idle), comparisonType):
                    result = HumanStates.Idle;
                    return true;
                case { } s when s.Equals(nameof(HumanStates.Working), comparisonType):
                    result = HumanStates.Working;
                    return true;
                case { } s when s.Equals(nameof(HumanStates.Sleeping), comparisonType):
                    result = HumanStates.Sleeping;
                    return true;
                case { } s when s.Equals(nameof(HumanStates.Eating), comparisonType):
                    result = HumanStates.Eating;
                    return true;
                case { } s when s.Equals(nameof(HumanStates.Dead), comparisonType):
                    result = HumanStates.Dead;
                    return true;
                case { } s when Int32.TryParse(s, out var val):
                    result = (HumanStates)val;
                    return true;
                default:
                    result = default;
                    return false;
            }
        }

        public static bool TryParseIgnoreCase(
            [NotNullWhen(true)] string? name,
            out HumanStates result)
        {
            return TryParse(name, StringComparison.OrdinalIgnoreCase, out result);
        }

        public static bool TryParse(
            [NotNullWhen(true)] string? name,
            out HumanStates result)
        {
            switch (name)
            {
                case nameof(HumanStates.Idle):
                    result = HumanStates.Idle;
                    return true;
                case nameof(HumanStates.Working):
                    result = HumanStates.Working;
                    return true;
                case nameof(HumanStates.Sleeping):
                    result = HumanStates.Sleeping;
                    return true;
                case nameof(HumanStates.Eating):
                    result = HumanStates.Eating;
                    return true;
                case nameof(HumanStates.Dead):
                    result = HumanStates.Dead;
                    return true;
                case { } s when Int32.TryParse(s, out var val):
                    result = (HumanStates)val;
                    return true;
                default:
                    result = default;
                    return false;
            }
        }

        public static HumanStates[] GetValues()
        {
            return new[]
            {
                HumanStates.Idle,
                HumanStates.Working,
                HumanStates.Sleeping,
                HumanStates.Eating,
                HumanStates.Dead,
            };
        }

        public static string[] GetNames()
        {
            return new[]
            {
                nameof(HumanStates.Idle),
                nameof(HumanStates.Working),
                nameof(HumanStates.Sleeping),
                nameof(HumanStates.Eating),
                nameof(HumanStates.Dead),
            };
        }
    }
}
