//HintName: HumanStatesExtensions.g.cs
// <auto-generated />
#nullable enable

using System;

#pragma warning disable CS1591 // publicly visible type or member must be documented

namespace TestNamespace
{
    public static partial class HumanStatesExtensions
    {
        public static string ToStringFast(this HumanStates value)
        {
            return value switch
            {
                HumanStates.Idle => nameof(HumanStates.Idle),
                HumanStates.Working => nameof(HumanStates.Working),
                HumanStates.Sleeping => nameof(HumanStates.Sleeping),
                HumanStates.Eating => nameof(HumanStates.Eating),
                HumanStates.Dead => nameof(HumanStates.Dead),
                _ => value.ToString()
            };
        }

        public static bool IsDefined(this HumanStates value)
        {
            return HumanStatesValidation.IsDefined(value);
        }
    }
}
