//HintName: ColourValidation.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

#pragma warning disable CS1591 // publicly visible type or member must be documented

namespace TestNamespace
{
    public static partial class ColourValidation
    {
        public static bool IsDefined(Colour value)
        {
            return value switch
            {
                Colour.Red => true,
                Colour.Blue => true,
                _ => false
            };
        }

        public static bool IsDefined(
            [NotNullWhen(true)] string? name,
            StringComparison comparisonType)
        {
            return name switch
            {
                { } s when s.Equals(nameof(Colour.Red), comparisonType) => true,
                { } s when s.Equals(nameof(Colour.Blue), comparisonType) => true,
                _ => false
            };
        }

        public static bool IsDefinedIgnoreCase([NotNullWhen(true)] string? name)
        {
            return IsDefined(name, StringComparison.OrdinalIgnoreCase);
        }

        public static bool IsDefined([NotNullWhen(true)] string? name)
        {
            return name switch
            {
                nameof(Colour.Red) => true,
                nameof(Colour.Blue) => true,
                _ => false
            };
        }
    }
}
