name: Create tag

on:
  workflow_dispatch:

env:
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

permissions:
  contents: read

jobs:
  create-tag:
    if: github.actor == 'skarllot'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 🛡️ Harden Runner
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        disable-sudo-and-containers: true
        egress-policy: block
        allowed-endpoints: >
          *.azureedge.net:443
          aka.ms:443
          github.com:443
          api.nuget.org:443
          builds.dotnet.microsoft.com:443
          ci.dot.net:443

    - name: 🛒 Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        global-json-file: global.json

    - name: 🛠️ Setup Nerdbank.GitVersioning
      run: dotnet tool restore

    - name: 🏷️ Tag release
      run: dotnet nbgv tag

    - name: 🚀 Push Git tags
      run: git push --tags