// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Raiqub.Generators.EnumUtilities.CodeWriters
{
    using Common;
    using Models;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EnumFactoryWriter : CodeWriterBase<EnumToGenerate>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n// <auto-generated />\r\n#nullable enable\r\n\r\nusing System;\r\nusing System.Diagnostics.CodeAnalysis;\r\nusing System.Globalization;\r\n\r\n#pragma warning disable CS1591 // publicly visible type or member must be documented\r\n\r\n");
            
            #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"

    if (!string.IsNullOrEmpty(Model.Namespace))
    {
        WriteLine($"namespace {Model.Namespace}");
        WriteLine("{");
        PushIndent();
    }

            
            #line default
            #line hidden
            this.Write("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]\r\n[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"");
            
            #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentAssemblyName.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Append($"{CurrentAssemblyName.Version}")));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IsPublic ? "public" : "internal"));
            
            #line default
            #line hidden
            this.Write(" static partial class ");
            
            #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Factory\r\n{\r\n");
            
            #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"

    WriteDefaultBlock();
    WriteEnumMemberBlock();
    WriteDescriptionBlock();
    WriteDisplayBlock();
    WriteMiscellaneousBlock();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 39 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"

    if (!string.IsNullOrEmpty(Model.Namespace))
    {
        PopIndent();
        WriteLine("}");
    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"

    private void WriteDefaultBlock()
    {

        
        #line default
        #line hidden
        
        #line 5 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("    /// <summary>\r\n    /// Converts the string representation of the name or numeric value of one or more enumerated constants to\r\n    /// an equivalent enumerated object. The return value indicates whether the conversion succeeded.\r\n    /// </summary>\r\n    /// <param name=\"name\">The case-sensitive string representation of the enumeration name or underlying value to convert.</param>\r\n    /// <param name=\"comparisonType\">One of the enumeration values that specifies how the strings will be compared.</param>\r\n    /// <param name=\"result\">\r\n    /// When this method returns, result contains an object of type ");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" whose value is represented by value\r\n    /// if the parse operation succeeds. If the parse operation fails, result contains the default value of the\r\n    /// underlying type of ");

        
        #line default
        #line hidden
        
        #line 14 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 14 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(". Note that this value need not be a member of the ");

        
        #line default
        #line hidden
        
        #line 14 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 14 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" enumeration.\r\n    /// </param>\r\n    /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>\r\n    /// <exception cref=\"ArgumentException\"><paramref name=\"comparisonType\"/> is not a <see cref=\"StringComparison\"/> value.</exception>\r\n    public static bool TryParse(\r\n        [NotNullWhen(true)] string? name,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (name)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"

    foreach (var curr in Model.Values)
    {

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("            case { } s when s.Equals(nameof(");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("), comparisonType):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 35 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("            case { } s when TryParseNumeric(s, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 35 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 35 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" val):\r\n                result = (");

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(")val;\r\n                return true;\r\n            default:\r\n                return Enum.TryParse(name, out result);\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the name or numeric value of one or more enumerated constants to\r\n    /// an equivalent enumerated object. The return value indicates whether the conversion succeeded.\r\n    /// </summary>\r\n    /// <param name=\"name\">The case-sensitive string representation of the enumeration name or underlying value to convert.</param>\r\n    /// <param name=\"result\">\r\n    /// When this method returns, result contains an object of type ");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" whose value is represented by value\r\n    /// if the parse operation succeeds. If the parse operation fails, result contains the default value of the\r\n    /// underlying type of ");

        
        #line default
        #line hidden
        
        #line 51 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 51 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(". Note that this value need not be a member of the ");

        
        #line default
        #line hidden
        
        #line 51 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 51 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" enumeration.\r\n    /// </param>\r\n    /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>\r\n    public static bool TryParse(\r\n        [NotNullWhen(true)] string? name,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (name)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"

    foreach (var curr in Model.Values)
    {

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("            case nameof(");

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 67 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("            case { } s when TryParseNumeric(s, StringComparison.Ordinal, out ");

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" val):\r\n                result = (");

        
        #line default
        #line hidden
        
        #line 71 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 71 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(")val;\r\n                return true;\r\n            default:\r\n                return Enum.TryParse(name, out result);\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the name or numeric value of one or more enumerated constants to\r\n    /// an equivalent enumerated object. The return value indicates whether the conversion succeeded.\r\n    /// </summary>\r\n    /// <param name=\"name\">The case-sensitive string representation of the enumeration name or underlying value to convert.</param>\r\n    /// <param name=\"result\">\r\n    /// When this method returns, result contains an object of type ");

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" whose value is represented by value\r\n    /// if the parse operation succeeds. If the parse operation fails, result contains the default value of the\r\n    /// underlying type of ");

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(". Note that this value need not be a member of the ");

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" enumeration.\r\n    /// </param>\r\n    /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>\r\n    public static bool TryParseIgnoreCase(\r\n        [NotNullWhen(true)] string? name,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 91 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 91 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        return TryParse(name, StringComparison.OrdinalIgnoreCase, out result);\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the name or numeric value of one or more enumerated constants to\r\n    /// an equivalent enumerated object.\r\n    /// </summary>\r\n    /// <param name=\"name\">The case-sensitive string representation of the enumeration name or underlying value to convert.</param>\r\n    /// <returns>\r\n    /// Contains an object of type ");

        
        #line default
        #line hidden
        
        #line 102 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 102 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" whose value is represented by value if the parse operation succeeds.\r\n    /// If the parse operation fails, result contains <c>null</c> value.\r\n    /// </returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 105 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 105 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("? TryParse(string? name)\r\n    {\r\n        return TryParse(name, out ");

        
        #line default
        #line hidden
        
        #line 107 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 107 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the name or numeric value of one or more enumerated constants to\r\n    /// an equivalent enumerated object.\r\n    /// </summary>\r\n    /// <param name=\"name\">The case-sensitive string representation of the enumeration name or underlying value to convert.</param>\r\n    /// <returns>\r\n    /// Contains an object of type ");

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" whose value is represented by value if the parse operation succeeds.\r\n    /// If the parse operation fails, result contains <c>null</c> value.\r\n    /// </returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("? TryParseIgnoreCase(string? name)\r\n    {\r\n        return TryParse(name, StringComparison.OrdinalIgnoreCase, out ");

        
        #line default
        #line hidden
        
        #line 121 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 121 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the name or numeric value of one or more enumerated constants to\r\n    /// an equivalent enumerated object.\r\n    /// </summary>\r\n    /// <param name=\"name\">The case-sensitive string representation of the enumeration name or underlying value to convert.</param>\r\n    /// <param name=\"comparisonType\">One of the enumeration values that specifies how the strings will be compared.</param>\r\n    /// <returns>\r\n    /// Contains an object of type ");

        
        #line default
        #line hidden
        
        #line 131 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 131 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" whose value is represented by value if the parse operation succeeds.\r\n    /// If the parse operation fails, result contains <c>null</c> value.\r\n    /// </returns>\r\n    /// <exception cref=\"ArgumentException\"><paramref name=\"comparisonType\"/> is not a <see cref=\"StringComparison\"/> value.</exception>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 135 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 135 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write("? TryParse(string? name, StringComparison comparisonType)\r\n    {\r\n        return TryParse(name, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 137 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 137 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 139 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DefaultBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"

    private void WriteEnumMemberBlock()
    {
        if (!Model.HasSerializationValue)
            return;

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write("\r\n    /// <summary>\r\n    /// Converts the string representation of the value associated with one enumerated constant to\r\n    /// an equivalent enumerated object. The return value indicates whether the conversion succeeded.\r\n    /// </summary>\r\n    /// <param name=\"enumMemberValue\">The value as defined with <see cref=\"System.Runtime.Serialization.EnumMemberAttribute\"/>.</param>\r\n    /// <param name=\"comparisonType\">One of the enumeration values that specifies how the strings will be compared.</param>\r\n    /// <param name=\"result\">\r\n    /// When this method returns, result contains an object of type ");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" whose value is represented by value\r\n    /// if the parse operation succeeds. If the parse operation fails, result contains the default value of the\r\n    /// underlying type of ");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(". Note that this value need not be a member of the ");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" enumeration.\r\n    /// </param>\r\n    /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>\r\n    /// <exception cref=\"ArgumentException\"><paramref name=\"comparisonType\"/> is not a <see cref=\"StringComparison\"/> value.</exception>\r\n    public static bool TryParseFromEnumMemberValue(\r\n        [NotNullWhen(true)] string? enumMemberValue,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (enumMemberValue)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"

        foreach (var curr in Model.Values)
        {

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write("            case { } s when s.Equals(");

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.SerializationValue != null
                        ? Append($"\"{curr.SerializationValue}\"")
                        : Append($"nameof({Model.RefName}.{curr.MemberName})")));

        
        #line default
        #line hidden
        
        #line 35 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(", comparisonType):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 41 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write("            default:\r\n                result = default;\r\n                return false;\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the value associated with one enumerated constant to\r\n    /// an equivalent enumerated object. The return value indicates whether the conversion succeeded.\r\n    /// </summary>\r\n    /// <param name=\"enumMemberValue\">The value as defined with <see cref=\"System.Runtime.Serialization.EnumMemberAttribute\"/>.</param>\r\n    /// <param name=\"result\">\r\n    /// When this method returns, result contains an object of type ");

        
        #line default
        #line hidden
        
        #line 53 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 53 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" whose value is represented by value\r\n    /// if the parse operation succeeds. If the parse operation fails, result contains the default value of the\r\n    /// underlying type of ");

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(". Note that this value need not be a member of the ");

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" enumeration.\r\n    /// </param>\r\n    /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>\r\n    public static bool TryParseFromEnumMemberValue([NotNullWhen(true)] string? enumMemberValue, out ");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        return TryParseFromEnumMemberValue(enumMemberValue, StringComparison.Ordinal, out result);\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the value associated with one enumerated constant to\r\n    /// an equivalent enumerated object.\r\n    /// </summary>\r\n    /// <param name=\"enumMemberValue\">The value as defined with <see cref=\"System.Runtime.Serialization.EnumMemberAttribute\"/>.</param>\r\n    /// <param name=\"comparisonType\">One of the enumeration values that specifies how the strings will be compared.</param>\r\n    /// <returns>\r\n    /// Contains an object of type ");

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" whose value is represented by value if the parse operation succeeds.\r\n    /// If the parse operation fails, result contains a null value.\r\n    /// </returns>\r\n    /// <exception cref=\"ArgumentException\"><paramref name=\"comparisonType\"/> is not a <see cref=\"StringComparison\"/> value.</exception>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 74 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 74 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write("? TryParseFromEnumMemberValue(string? enumMemberValue, StringComparison comparisonType)\r\n    {\r\n        return TryParseFromEnumMemberValue(enumMemberValue, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 76 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 76 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    /// <summary>\r\n    /// Converts the string representation of the value associated with one enumerated constant to\r\n    /// an equivalent enumerated object.\r\n    /// </summary>\r\n    /// <param name=\"enumMemberValue\">The value as defined with <see cref=\"System.Runtime.Serialization.EnumMemberAttribute\"/>.</param>\r\n    /// <returns>\r\n    /// Contains an object of type ");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" whose value is represented by value if the parse operation succeeds.\r\n    /// If the parse operation fails, result contains a null value.\r\n    /// </returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 88 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 88 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write("? TryParseFromEnumMemberValue(string? enumMemberValue)\r\n    {\r\n        return TryParseFromEnumMemberValue(enumMemberValue, StringComparison.Ordinal, out ");

        
        #line default
        #line hidden
        
        #line 90 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 90 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\EnumMemberBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"

    private void WriteDescriptionBlock()
    {
        if (!Model.HasDescription)
            return;

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write("\r\n    public static bool TryCreateFromDescription(\r\n        [NotNullWhen(true)] string? description,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 11 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 11 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (description)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"

        foreach (var curr in Model.Values.Where(x => x.Description != null))
        {

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write("            case { } s when s.Equals(\"");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Description));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write("\", comparisonType):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 22 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write("            default:\r\n                result = default;\r\n                return false;\r\n        }\r\n    }\r\n\r\n    public static bool TryCreateFromDescription([NotNullWhen(true)] string? description, out ");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        return TryCreateFromDescription(description, StringComparison.Ordinal, out result);\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 36 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write("? TryCreateFromDescription(string? description, StringComparison comparisonType)\r\n    {\r\n        return TryCreateFromDescription(description, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 41 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 41 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write("? TryCreateFromDescription(string? description)\r\n    {\r\n        return TryCreateFromDescription(description, StringComparison.Ordinal, out ");

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 45 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DescriptionBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

    private void WriteDisplayBlock()
    {
        if (Model.HasDisplayName)
        {

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("\r\n    public static bool TryCreateFromDisplayShortName(\r\n        [NotNullWhen(true)] string? displayShortName,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 11 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 11 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (displayShortName)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

            foreach (var curr in Model.Values.Where(x => x.Display?.ShortName != null))
            {

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("            case { } s when s.Equals(");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display!.ResourceShortName != null
                            ? Append(curr.Display.ResourceShortName)
                            : Append($"\"{curr.Display.ShortName}\"")));

        
        #line default
        #line hidden
        
        #line 22 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(", comparisonType):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("            default:\r\n                return TryCreateFromDisplayName(displayShortName, comparisonType, out result);\r\n        }\r\n    }\r\n\r\n    public static bool TryCreateFromDisplayShortName([NotNullWhen(true)] string? displayShortName, out ");

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        return TryCreateFromDisplayShortName(displayShortName, StringComparison.Ordinal, out result);\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("? TryCreateFromDisplayShortName(string? displayShortName, StringComparison comparisonType)\r\n    {\r\n        return TryCreateFromDisplayShortName(displayShortName, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("? TryCreateFromDisplayShortName(string? displayShortName)\r\n    {\r\n        return TryCreateFromDisplayShortName(displayShortName, StringComparison.Ordinal, out ");

        
        #line default
        #line hidden
        
        #line 45 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 45 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    public static bool TryCreateFromDisplayName(\r\n        [NotNullWhen(true)] string? displayName,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 51 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 51 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (displayName)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

            foreach (var curr in Model.Values)
            {

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("            case { } s when s.Equals(");

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display?.ResourceName != null
                            ? Append(curr.Display.ResourceName)
                            : curr.Display?.Name != null
                                ? Append($"\"{curr.Display.Name}\"")
                                : Append($"nameof({Model.RefName}.{curr.MemberName})")));

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(", comparisonType):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 67 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("            default:\r\n                result = default;\r\n                return false;\r\n        }\r\n    }\r\n\r\n    public static bool TryCreateFromDisplayName([NotNullWhen(true)] string? displayName, out ");

        
        #line default
        #line hidden
        
        #line 76 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 76 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        return TryCreateFromDisplayName(displayName, StringComparison.Ordinal, out result);\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("? TryCreateFromDisplayName(string? displayName, StringComparison comparisonType)\r\n    {\r\n        return TryCreateFromDisplayName(displayName, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("? TryCreateFromDisplayName(string? displayName)\r\n    {\r\n        return TryCreateFromDisplayName(displayName, StringComparison.Ordinal, out ");

        
        #line default
        #line hidden
        
        #line 88 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 88 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 90 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

        if (Model.HasDisplayDescription)
        {

        
        #line default
        #line hidden
        
        #line 98 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("\r\n    public static bool TryCreateFromDescription(\r\n        [NotNullWhen(true)] string? description,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 101 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 101 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (description)\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 105 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

            foreach (var curr in Model.Values.Where(x => x.Display?.Description != null))
            {

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("            case { } s when s.Equals(");

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display!.ResourceDescription != null
                            ? Append(curr.Display.ResourceDescription)
                            : Append($"\"{curr.Display.Description}\"")));

        
        #line default
        #line hidden
        
        #line 112 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(", comparisonType):\r\n                result = ");

        
        #line default
        #line hidden
        
        #line 113 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 113 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 113 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 113 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(";\r\n                return true;\r\n");

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 118 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("            default:\r\n                result = default;\r\n                return false;\r\n        }\r\n    }\r\n\r\n    public static bool TryCreateFromDescription([NotNullWhen(true)] string? description, out ");

        
        #line default
        #line hidden
        
        #line 124 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 124 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        return TryCreateFromDescription(description, StringComparison.Ordinal, out result);\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 129 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 129 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("? TryCreateFromDescription(string? description, StringComparison comparisonType)\r\n    {\r\n        return TryCreateFromDescription(description, comparisonType, out ");

        
        #line default
        #line hidden
        
        #line 131 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 131 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 134 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 134 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write("? TryCreateFromDescription(string? description)\r\n    {\r\n        return TryCreateFromDescription(description, StringComparison.Ordinal, out ");

        
        #line default
        #line hidden
        
        #line 136 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 136 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"
this.Write(" result) ? result : null;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 138 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\DisplayBlock.ttinclude"

        }
    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"

    private void WriteMiscellaneousBlock()
    {

        
        #line default
        #line hidden
        
        #line 6 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("\r\n    /// <summary>Retrieves an array of the values of the constants in the ");

        
        #line default
        #line hidden
        
        #line 6 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 6 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(" enumeration.</summary>\r\n    /// <returns>An array that contains the values of the constants in ");

        
        #line default
        #line hidden
        
        #line 7 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 7 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("[] GetValues()\r\n    {\r\n        return new[]\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"

    foreach (var curr in Model.UniqueValues)
    {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("        };\r\n    }\r\n\r\n    /// <summary>Retrieves an array of the names of the constants in ");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(" enumeration.</summary>\r\n    /// <returns>A string array of the names of the constants in ");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".</returns>\r\n    public static string[] GetNames()\r\n    {\r\n        return new[]\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"

    foreach (var curr in Model.Values)
    {

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("            nameof(");

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 33 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("),\r\n");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 37 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write("        };\r\n    }\r\n\r\n    private static bool TryParseNumeric(\r\n        string name,\r\n        StringComparison comparisonType,\r\n        out ");

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(" result)\r\n    {\r\n        switch (comparisonType)\r\n        {\r\n            case StringComparison.CurrentCulture:\r\n            case StringComparison.CurrentCultureIgnoreCase:\r\n                return ");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".TryParse(name, NumberStyles.Integer, NumberFormatInfo.CurrentInfo, out result);\r\n            case StringComparison.InvariantCulture:\r\n            case StringComparison.InvariantCultureIgnoreCase:\r\n            case StringComparison.Ordinal:\r\n            case StringComparison.OrdinalIgnoreCase:\r\n                return ");

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".TryParse(name, NumberStyles.Integer, NumberFormatInfo.InvariantInfo, out result);\r\n            default:\r\n                return ");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"
this.Write(".TryParse(name, out result);\r\n        }\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Factory\MiscellaneousBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumFactoryWriter.tt"

    public EnumFactoryWriter(StringBuilder builder) : base(builder)
    {
    }

    public override string GetFileName() => $"{Model.Namespace ?? "_"}.{Model.Name}Factory.g.cs";

    protected override bool CanGenerateFor(EnumToGenerate model) =>
        (model.SelectedGenerators & SelectedGenerators.MainGenerator) != 0;

        
        #line default
        #line hidden
    }
    
}
