// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Raiqub.Generators.EnumUtilities.CodeWriters
{
    using Common;
    using Models;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EnumExtensionsWriter : CodeWriterBase<EnumToGenerate>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

#nullable enable

            
            #line default
            #line hidden
            this.Write("// <auto-generated />\r\n#nullable enable\r\n\r\nusing System;\r\n");
            
            #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

            if (IsInterlockedSupported())
            {

            
            #line default
            #line hidden
            this.Write("using System.Runtime.CompilerServices;\r\nusing System.Threading;\r\n");
            
            #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

            }

            
            #line default
            #line hidden
            this.Write("\r\n#pragma warning disable CS1591 // publicly visible type or member must be documented\r\n\r\n");
            
            #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

            if (!string.IsNullOrEmpty(Model.Namespace))
            {
                WriteLine($"namespace {Model.Namespace}");
                WriteLine("{");
                PushIndent();
            }

            
            #line default
            #line hidden
            this.Write("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]\r\n[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"");
            
            #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentAssemblyName.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 38 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Append($"{CurrentAssemblyName.Version}")));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 39 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IsPublic ? "public" : "internal"));
            
            #line default
            #line hidden
            this.Write(" static partial class ");
            
            #line 39 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Extensions\r\n{\r\n");
            
            #line 41 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

            WriteDefaultBlock();
            WriteInterlockedBlock();
            WriteEnumMemberBlock();
            WriteDescriptionBlock();
            WriteDisplayBlock();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

            if (!string.IsNullOrEmpty(Model.Namespace))
            {
                PopIndent();
                WriteLine("}");
            }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

    private void WriteDefaultBlock()
    {

        
        #line default
        #line hidden
        
        #line 5 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("    /// <summary>Converts the value of this instance to its equivalent string representation.</summary>\r\n    /// <returns>The string representation of the value of this instance.</returns>\r\n    public static string ToStringFast(this ");

        
        #line default
        #line hidden
        
        #line 7 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 7 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return (");

        
        #line default
        #line hidden
        
        #line 9 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 9 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(")value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 11 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

    foreach (var curr in Model.UniqueValues)
    {

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberValue));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(" => \"");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("\",\r\n");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("            _ => value.ToString()\r\n        };\r\n    }\r\n\r\n    /// <summary>Returns a boolean telling whether the value of this instance exists in the enumeration.</summary>\r\n    /// <returns><c>true</c> if the value of this instance exists in the enumeration; <c>false</c> otherwise.</returns>\r\n    public static bool IsDefined(this ");

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return ");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("Validation.IsDefined(value);\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"

    private void WriteInterlockedBlock()
    {
        string? underlyingType = GetInterlockedUnderlyingType();
        if (underlyingType is null)
            return;

        if (Model.IsFlags)
        {

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write("\r\n#if NET5_0_OR_GREATER\r\n    /// <summary>Bitwise \"ands\" two enumerations and replaces the first value with the result, as an atomic operation.</summary>\r\n    /// <param name=\"location\">A variable containing the first value to be combined.</param>\r\n    /// <param name=\"value\">The value to be combined with the value at <paramref name=\"location\" />.</param>\r\n    /// <returns>The original value in <paramref name=\"location\" />.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedAnd(this ref ");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location, ");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.And(ref locationRaw, Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref value));\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n\r\n    /// <summary>Bitwise \"ors\" two enumerations and replaces the first value with the result, as an atomic operation.</summary>\r\n    /// <param name=\"location\">A variable containing the first value to be combined.</param>\r\n    /// <param name=\"value\">The value to be combined with the value at <paramref name=\"location\" />.</param>\r\n    /// <returns>The original value in <paramref name=\"location\" />.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedOr(this ref ");

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location, ");

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.Or(ref locationRaw, Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref value));\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n#endif\r\n");

        
        #line default
        #line hidden
        
        #line 35 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"

        }

        if (!Model.IsFlags)
        {

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write("\r\n    /// <summary>Adds two enumerations and replaces the first integer with the sum, as an atomic operation.</summary>\r\n    /// <param name=\"location\">A variable containing the first value to be added.</param>\r\n    /// <param name=\"value\">The value to be added to the enumeration at <paramref name=\"location\" />.</param>\r\n    /// <returns>The new value that was stored at <paramref name=\"location\" /> by this operation.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedAdd(this ref ");

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location, ");

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.Add(ref locationRaw, value);\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 50 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 50 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 50 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 50 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n\r\n    /// <summary>Decrements enumeration and stores the result, as an atomic operation.</summary>\r\n    /// <param name=\"location\">The variable whose value is to be decremented.</param>\r\n    /// <returns>The value of the variable immediately after the decrement operation finished.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedDecrement(this ref ");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.Decrement(ref locationRaw);\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n\r\n    /// <summary>Increments enumeration and stores the result, as an atomic operation.</summary>\r\n    /// <param name=\"location\">The variable whose value is to be incremented.</param>\r\n    /// <returns>The value of the variable immediately after the increment operation finished.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedIncrement(this ref ");

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 69 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 69 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.Increment(ref locationRaw);\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 70 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 76 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write("\r\n    /// <summary>Compares two enumerations for equality and, if they are equal, replaces the first value.</summary>\r\n    /// <param name=\"location\">The destination, whose value is compared with <paramref name=\"comparand\" /> and possibly replaced.</param>\r\n    /// <param name=\"value\">The value that replaces the destination value if the comparison results in equality.</param>\r\n    /// <param name=\"comparand\">The value that is compared to the value at <paramref name=\"location\" />.</param>\r\n    /// <returns>The original value in <paramref name=\"location\" />.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedCompareExchange(this ref ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location, ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" value, ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" comparand)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.CompareExchange(ref locationRaw, Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref value), Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref comparand));\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n\r\n    /// <summary>Sets an enumeration value to a specified value and returns the original value, as an atomic operation.</summary>\r\n    /// <param name=\"location\">The variable to set to the specified value.</param>\r\n    /// <param name=\"value\">The value to which the <paramref name=\"location\" /> parameter is set.</param>\r\n    /// <returns>The original value of <paramref name=\"location\" />.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedExchange(this ref ");

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location, ");

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.Exchange(ref locationRaw, Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref value));\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 96 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 96 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 96 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 96 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 98 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"

        if (underlyingType == "long")
        {

        
        #line default
        #line hidden
        
        #line 103 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write("\r\n    /// <summary>Returns a 64-bit enumeration value, loaded as an atomic operation.</summary>\r\n    /// <param name=\"location\">The 64-bit enumeration value to be loaded.</param>\r\n    /// <returns>The loaded value.</returns>\r\n    public static ");

        
        #line default
        #line hidden
        
        #line 106 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 106 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" InterlockedRead(this ref ");

        
        #line default
        #line hidden
        
        #line 106 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 106 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" location)\r\n    {\r\n        ref ");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" locationRaw = ref Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref location);\r\n        ");

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(" resultRaw = Interlocked.Read(ref locationRaw);\r\n        return Unsafe.As<");

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(underlyingType));

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"
this.Write(">(ref resultRaw);\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 112 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\InterlockedBlock.ttinclude"

        }
    }

    private string? GetInterlockedUnderlyingType()
    {
        return Model.UnderlyingType switch
        {
            "int" => "int",
            "long" => "long",
            "uint" => "int",
            "ulong" => "long",
            _ => null
            };
    }

    private bool IsInterlockedSupported() => GetInterlockedUnderlyingType() != null;

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

    private void WriteEnumMemberBlock()
    {
        if (!Model.HasSerializationValue)
            return;

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write("\r\n    public static string ToEnumMemberValue(this ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return (");

        
        #line default
        #line hidden
        
        #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(")value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

        foreach (var curr in Model.UniqueValues)
        {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberValue));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.SerializationValue != null
                        ? Append($"\"{curr.SerializationValue}\"")
                        : Append($"\"{curr.MemberName}\"")));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write("            _ => value.ToString()\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

    private void WriteDescriptionBlock()
    {
        if (!Model.HasDescription)
            return;

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("\r\n    public static string? GetDescription(this ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return (");

        
        #line default
        #line hidden
        
        #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(")value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

        foreach (var curr in Model.UniqueValues.Where(x => x.Description != null))
        {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberValue));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(" => \"");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Description));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("\",\r\n");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("            _ => null\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

    private void WriteDisplayBlock()
    {
        if (Model.HasDisplayName)
        {

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("\r\n    public static string GetDisplayShortName(this ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return (");

        
        #line default
        #line hidden
        
        #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 10 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(")value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            foreach (var curr in Model.UniqueValues.Where(x => x.Display?.ShortName != null))
            {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberValue));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display!.ResourceShortName != null
                                                                   ? Append(curr.Display.ResourceShortName)
                                                                   : Append($"\"{curr.Display.ShortName}\"")));

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 22 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            _ => GetDisplayName(value)\r\n        };\r\n    }\r\n\r\n    public static string GetDisplayName(this ");

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return (");

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(")value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            foreach (var curr in Model.UniqueValues)
            {

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberValue));

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display?.ResourceName != null
                            ? Append(curr.Display.ResourceName)
                            : curr.Display?.Name != null
                                ? Append($"\"{curr.Display.Name}\"")
                                : Append($"\"{curr.MemberName}\"")));

        
        #line default
        #line hidden
        
        #line 39 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            _ => value.ToString()\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

        if (Model.HasDisplayDescription)
        {

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("\r\n    public static string? GetDescription(this ");

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return (");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.UnderlyingType));

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(")value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            foreach (var curr in Model.UniqueValues.Where(x => x.Display?.Description != null))
            {

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberValue));

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display!.ResourceDescription != null
                            ? Append(curr.Display.ResourceDescription)
                            : Append($"\"{curr.Display.Description}\"")));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 69 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            _ => null\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

        }
    }

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

    public EnumExtensionsWriter(StringBuilder builder) : base(builder)
    {
    }

    public override string GetFileName() => $"{Model.Namespace ?? "_"}.{Model.Name}Extensions.g.cs";

    protected override bool CanGenerateFor(EnumToGenerate model) =>
        (model.SelectedGenerators & SelectedGenerators.MainGenerator) != 0;

        
        #line default
        #line hidden
    }
    
}
