// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Raiqub.Generators.EnumUtilities.CodeWriters
{
    using Common;
    using Models;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EnumExtensionsWriter : CodeWriterBase<EnumToGenerate>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n// <auto-generated />\r\n#nullable enable\r\n\r\nusing System;\r\n\r\n#pragma warning disable CS1591 // publicly visible type or member must be documented\r\n\r\n");
            
            #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

    if (!string.IsNullOrEmpty(Model.Namespace))
    {
        WriteLine($"namespace {Model.Namespace}");
        WriteLine("{");
        PushIndent();
    }

            
            #line default
            #line hidden
            this.Write("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]\r\n[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"");
            
            #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentAssemblyName.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Append($"{CurrentAssemblyName.Version}")));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IsPublic ? "public" : "internal"));
            
            #line default
            #line hidden
            this.Write(" static partial class ");
            
            #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Extensions\r\n{\r\n");
            
            #line 28 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

    WriteDefaultBlock();
    WriteEnumMemberBlock();
    WriteDescriptionBlock();
    WriteDisplayBlock();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 35 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

    if (!string.IsNullOrEmpty(Model.Namespace))
    {
        PopIndent();
        WriteLine("}");
    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

    private void WriteDefaultBlock()
    {

        
        #line default
        #line hidden
        
        #line 5 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("    /// <summary>Converts the value of this instance to its equivalent string representation.</summary>\r\n    /// <returns>The string representation of the value of this instance.</returns>\r\n    public static string ToStringFast(this ");

        
        #line default
        #line hidden
        
        #line 7 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 7 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 11 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

    foreach (var curr in Model.UniqueValues)
    {

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(" => nameof(");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 15 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("),\r\n");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("            _ => value.ToString()\r\n        };\r\n    }\r\n\r\n    /// <summary>Returns a boolean telling whether the value of this instance exists in the enumeration.</summary>\r\n    /// <returns><c>true</c> if the value of this instance exists in the enumeration; <c>false</c> otherwise.</returns>\r\n    public static bool IsDefined(this ");

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return ");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"
this.Write("Validation.IsDefined(value);\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DefaultBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

    private void WriteEnumMemberBlock()
    {
        if (!Model.HasSerializationValue)
            return;

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write("\r\n    public static string ToEnumMemberValue(this ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

        foreach (var curr in Model.UniqueValues)
        {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.SerializationValue != null
                        ? Append($"\"{curr.SerializationValue}\"")
                        : Append($"nameof({Model.RefName}.{curr.MemberName})")));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"
this.Write("            _ => value.ToString()\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\EnumMemberBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

    private void WriteDescriptionBlock()
    {
        if (!Model.HasDescription)
            return;

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("\r\n    public static string? GetDescription(this ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

        foreach (var curr in Model.UniqueValues.Where(x => x.Description != null))
        {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(" => \"");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Description));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("\",\r\n");

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"
this.Write("            _ => null\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DescriptionBlock.ttinclude"

    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

    private void WriteDisplayBlock()
    {
        if (Model.HasDisplayName)
        {

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("\r\n    public static string GetDisplayShortName(this ");

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 8 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            foreach (var curr in Model.UniqueValues.Where(x => x.Display?.ShortName != null))
            {

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display!.ResourceShortName != null
                                                                   ? Append(curr.Display.ResourceShortName)
                                                                   : Append($"\"{curr.Display.ShortName}\"")));

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 22 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            _ => GetDisplayName(value)\r\n        };\r\n    }\r\n\r\n    public static string GetDisplayName(this ");

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            foreach (var curr in Model.UniqueValues)
            {

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display?.ResourceName != null
                            ? Append(curr.Display.ResourceName)
                            : curr.Display?.Name != null
                                ? Append($"\"{curr.Display.Name}\"")
                                : Append($"nameof({Model.RefName}.{curr.MemberName})")));

        
        #line default
        #line hidden
        
        #line 39 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 43 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            _ => value.ToString()\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

        }

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

        if (Model.HasDisplayDescription)
        {

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("\r\n    public static string? GetDescription(this ");

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" value)\r\n    {\r\n        return value switch\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            foreach (var curr in Model.UniqueValues.Where(x => x.Display?.Description != null))
            {

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.RefName));

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.MemberName));

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(" => ");

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(curr.Display!.ResourceDescription != null
                            ? Append(curr.Display.ResourceDescription)
                            : Append($"\"{curr.Display.Description}\"")));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write(",\r\n");

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

            }

        
        #line default
        #line hidden
        
        #line 69 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"
this.Write("            _ => null\r\n        };\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\Extensions\DisplayBlock.ttinclude"

        }
    }

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\skarl\source\repos\github\skarllot\EnumUtilities\src\EnumUtilities\CodeWriters\EnumExtensionsWriter.tt"

    public EnumExtensionsWriter(StringBuilder builder) : base(builder)
    {
    }

    public override string GetFileName() => $"{Model.Namespace ?? "_"}.{Model.Name}Extensions.g.cs";

    protected override bool CanGenerateFor(EnumToGenerate model) =>
        (model.SelectedGenerators & SelectedGenerators.MainGenerator) != 0;

        
        #line default
        #line hidden
    }
    
}
